{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"Timed out retrying after 15000ms: Expected to find element: `[id=\"email_message\"]`, but never found it.","children":[{"name":"Validation errors shown if no credentials entered in Sign Up form","uid":"d92e2a7cc2b1171c","parentUid":"e326027ddb2ea3cfbe64ac124cceecd5","status":"failed","time":{"start":1712069071756,"stop":1712069091117,"duration":19361},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"e326027ddb2ea3cfbe64ac124cceecd5"},{"name":"The following error originated from your application code, not from Cypress.\n\n  > Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"The conditions header shown on the \"Terms & Conditions\" page","uid":"584ac0d8a6e18645","parentUid":"35d21e1f1e9eac25704742358326744e","status":"failed","time":{"start":1712069091127,"stop":1712069096760,"duration":5633},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"35d21e1f1e9eac25704742358326744e"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}],"name":"categories"}